In [1]:
import pandas as pd

# Data Cleaning & Validation
Checking data types, missing values, and duplicates before feature engineering.

In [2]:
df = pd.read_csv('../data/raw/raw_market_data.csv')

In [3]:
df.head()

,Date,Close,High,Low,Open,Volume,Ticker_Name
0,2016-06-13,8110.600098,8125.250000,8063.899902,8102.250000,169700,^NSEI
1,2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,^NSEI
2,2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,^NSEI
3,2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,^NSEI
4,2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,^NSEI

In [4]:
df.shape

(19752, 7)

In [5]:
df.size

138264

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19752 entries, 0 to 19751
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         19752 non-null  str
 1   Close        19752 non-null  float64
 2   High         19752 non-null  float64
 3   Low          19752 non-null  float64
 4   Open         19752 non-null  float64
 5   Volume       19752 non-null  int64
 6   Ticker_Name  19752 non-null  str
dtypes: float64(4), int64(1), str(2)
memory usage: 1.1 MB

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

In [8]:
df.head()

,Date,Close,High,Low,Open,Volume,Ticker_Name
0,2016-06-13,8110.600098,8125.250000,8063.899902,8102.250000,169700,^NSEI
1,2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,^NSEI
2,2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,^NSEI
3,2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,^NSEI
4,2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,^NSEI

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19752 entries, 0 to 19751
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         19752 non-null  datetime64[us]
 1   Close        19752 non-null  float64
 2   High         19752 non-null  float64
 3   Low          19752 non-null  float64
 4   Open         19752 non-null  float64
 5   Volume       19752 non-null  int64
 6   Ticker_Name  19752 non-null  str
dtypes: datetime64[us](1), float64(4), int64(1), str(1)
memory usage: 1.1 MB

In [10]:
df.describe()

,Date,Close,High,Low,Open,Volume
count,19752,19752.000000,19752.000000,19752.000000,19752.000000,1.975200e+04
mean,2021-06-12 03:12:27.995139,7358.706698,7408.965304,7307.194929,7361.747818,8.867007e+06
min,2016-06-13 00:00:00,104.390198,107.757614,95.422211,104.921909,0.000000e+00
25%,2018-12-11 00:00:00,581.671875,588.218565,576.056806,582.843905,8.193115e+05
50%,2021-06-15 00:00:00,1279.496399,1293.306008,1266.722229,1279.952060,4.331169e+06
75%,2023-12-11 00:00:00,4223.721558,4260.994515,4198.849838,4224.255815,1.161551e+07
max,2026-06-11 00:00:00,61550.800781,61764.851562,61100.898438,61660.851562,1.798102e+09
std,NaN,12760.058747,12838.639929,12677.560759,12762.721288,1.893814e+07

In [11]:
df.isna().sum()

Date           0
Close          0
High           0
Low            0
Open           0
Volume         0
Ticker_Name    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.to_csv('../data/processed/base_market_data.csv', index= False)